# Generated by Django 5.1.7 on 2026-04-06 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
                ('measure', models.CharField(choices=[('шт', 'Штуки'), ('л', 'Литры'), ('кг', 'Килограммы'), ('мг', 'Миллиграммы'), ('ст.л.', 'Ст. ложки')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='step/')),
            ],
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('paid', 'оплачено'), ('unpaid', 'не оплачено'), ('error', 'ошибка оплаты'), ('timeout', 'истекло время на оплату')], max_length=50)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recept.basket')),
            ],
        ),
        migrations.CreateModel(
            name='Recept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('decription', models.CharField(max_length=250)),
                ('hours', models.IntegerField()),
                ('status', models.CharField(choices=[('easy', 'Легко'), ('medium', 'Средне'), ('hard', 'Сложно')], max_length=7)),
                ('photo', models.ImageField(upload_to='recept/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('on_delete', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recept.category')),
            ],
        ),
        migrations.AddField(
            model_name='basket',
            name='recept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recept.recept'),
        ),
    ]
