# Generated by Django 5.1.7 on 2026-04-06 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recept', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recept',
            name='photo',
        ),
        migrations.CreateModel(
            name='ReceptPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='recept/')),
                ('recept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recept.recept')),
            ],
        ),
    ]
