# Generated by Django 5.1.7 on 2026-04-07 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recept', '0002_remove_recept_photo_receptphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='recept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recept.recept'),
        ),
    ]
