# Generated by Django 5.1.7 on 2026-04-06 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_recept'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recept',
        ),
    ]
