# Generated by Django 5.1.7 on 2026-04-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_delete_recept'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Обычный пользователь'), ('admin', 'Администратор')], default='user', max_length=20),
        ),
    ]
